meta_product_name: "Le Koinpost"
meta_title: "Le Koinpost - Transformez vos biodéchets"
meta_description: "Soyez bons avec la planète, elle vous le rendra"
meta_image: "open-graph-image.jpg" # should exist in `app/assets/images/`
twitter_account: "@OuCompost"   # required for Twitter Cards
